apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudcrew-ingress
  namespace: cloudcrew
  labels:
    name: cloudcrew-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx" # 사용할 Ingress Controller
spec:
  rules:
  - host: cloudcrew.site
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: front-end-service
            port: 
              number: 80
      - pathType: Prefix
        path: "/api"
        backend:
          service:
            name: back-end-service
            port:
              number: 80
