apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudcrew-ingress
  namespace: cloudcrew
  labels:
    name: cloudcrew-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx" # 사용할 Ingress Controller
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - cloudcrew'
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - cloudcrew.site
    secretName: cloudcrew-tls
  - hosts:
    - monitoring.cloudcrew.site
    secretName: monitoring-cloudcrew-tls
  rules:
  - host: cloudcrew.site
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: front-end-service
            port: 
              number: 80
      - pathType: Prefix
        path: "/api"
        backend:
          service:
            name: back-end-service
            port:
              number: 80
  - host: monitoring.cloudcrew.site
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: grafana
            port:
              number: 80

